---
title: "statistical_analysis"
---
```{r Load the data}
library(yaml)
library(feather)
library(lme4)
library(lmerTest)
library(simr)
library(car)
library(goft)
library(fitdistrplus)
library(MASS)
library(here)
library(GeneralizedHyperbolic)
library(retimes)
library(ghyp)

# Read the configuration file
config <- yaml.load_file("../config.yml")

# Read the R dataframe
r_dataframe_path <- here(config$r_dataframe)
df <- read_feather(r_dataframe_path)
df <- na.omit(df)

# Convert to factor
factors <- c("task_stage", "fixation_rate", "transition_ratio", "glance_ratio", "pupil_size", "avg_mental_workload", "high_engagement", "low_engagement", "distraction", "subject", "performance_level")
df[factors] <- lapply(df[factors], as.factor)
df
```


```{r Distribution analysis}
options(warn=-1)

subjects <-  unique(df$subject)

aic.output <- function(df){
  rt <- df$reaction_time
  # Fit different distributions
  fit.normal <- fitdist(rt, "norm");
  fit.weibull <- fitdist(rt, "weibull");
  fit.gamma <- fitdist(rt, "gamma");


  # Custom inverse gauss distribution fit
  dinvgauss <- function(x, u, l){
    ifelse(t==0, 0.0, sqrt(l/(2*pi*x^3))*exp(-l*(x-u)^2/(2*u^2*x)));
  }

  pinvgauss <- function(q, u, l){
    integrate(dinvgauss, 0, q, u, l, abs.tol=1E-5)$value;
  }

  qinvgauss <-  function(p, u, l){
    uniroot(function(x){pinvgauss(x, u, l) - p}, c(0, 5))$root;
  }

  fit.invgauss <- fitdist(rt,"invgauss", start=list(u=0.5,l=1.5));

  # Custom reci-normal distribution fit
  drecinorm <- function(x, u, s){
    ifelse(t==0, 0.0, 1/(x^2*s*sqrt(2*pi))*exp(-(u*x-1)^2/(2*x^2*s^2)));
  }

  precinorm <- function(q, u, s){
    integrate(drecinorm, 0, q, u, s, abs.tol=1E-5)$value;
  }

  qrecinorm <-  function(p, u, s){
    uniroot(function(x){precinorm(x, u, s) - p}, c(0, 5))$root;
  }

  fit.recinorm <- fitdist(rt,"recinorm", start=list(u=0.5,s=1.5));

  output <-  c(fit.normal$aic, fit.weibull$aic, fit.gamma$aic, fit.invgauss$aic, fit.recinorm$aic)

return(output)

}

out <-  c()
for (subject in subjects){
  df_temp <-  df[df$subject==subject, ]
  out <- rbind(out, aic.output(df_temp));
}
```


```{r}
aggregate(df[, 6], list(df$task_stage), mean)
```


```{r Average aic analysis}
processed <- out[out[,5]<0, ]
colMeans(processed)
```


```{r Visual analysis of reaction time}
rt <- df$reaction_time

plotdist(rt, histo = TRUE, demp = TRUE)

# Distribution analysis
qqp(rt, "lnorm")
qqp(rt, "norm")

beta <- fitdistr(rt, "beta", start=list(shape1=0.5, shape2=0.5))
qqp(rt, "beta", shape1 = beta$estimate[[1]], shape2 = beta$estimate[[2]])

gamma <- fitdistr(rt, "gamma")
qqp(rt, "gamma", shape = gamma$estimate[[1]], rate = gamma$estimate[[2]])

# Cullen and Frey graph
descdist(rt, discrete = FALSE, boot = 1000)

# Plot fitting
plot(fit.gamma)
plot(fit.exgauss)

```


```{r Mental workload analysis}
rt <-  df$mental_workload
plotdist(rt)
```


```{r Linear mixed models task type fixed effect}
rt <-  df$mental_workload
model1 <- lmer(rt ~ task_stage + (1 | subject), data = df)
summary(model1)
```


```{r Linear mixed models mental workload fixed effect}
df$performance_level <- relevel(df$performance_level, 'low_performer')
model2 <- glm(rt ~ performance_level, data = df, family=inverse.gaussian())
summary(model2)
```


```{r Linear mixed models subject random effect}
model3 <- lmer(rt ~ 1 + (1 | subject), data = df)
summary(model3)
```
